// <auto-generated />
namespace Library_CourseWorkDB.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addedValidationsToBook : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedValidationsToBook));
        
        string IMigrationMetadata.Id
        {
            get { return "201411101558460_addedValidationsToBook"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
