// <auto-generated />
namespace Library_CourseWorkDB.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class lab1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(lab1));
        
        string IMigrationMetadata.Id
        {
            get { return "201410091925063_lab1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
